name: Build and Test Headless
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build Packages
        run: |
          cd how-to/register-with-home
          npm install
          npm run build
          cd ../setup-automation-tests
          npm install
          npm run dist --workspaces
          cd examples/register-with-home-js
          npm install
          cd ../register-with-home-ts
          npm install
      - name: Run Server and JavaScript Tests with Mocha
        uses: BerniWittmann/background-server-action@v1.0.4
        with:
          build: npx fkill-cli :8080 OpenFin OpenFinRVM --force --silent
          start: npm run server --prefix how-to/register-with-home
          wait-on: 'http://localhost:8080/manifest.fin.json'
          command: npm run test-local-mocha --prefix how-to/setup-automation-tests/examples/register-with-home-js
      - name: Run Server and JavaScript Tests with Jasmine
        uses: BerniWittmann/background-server-action@v1.0.4
        with:
          build: npx fkill-cli :8080 OpenFin OpenFinRVM --force --silent
          start: npm run server --prefix how-to/register-with-home
          wait-on: 'http://localhost:8080/manifest.fin.json'
          command: npm run test-local-jasmine --prefix how-to/setup-automation-tests/examples/register-with-home-js
      - name: Run Server and JavaScript Tests with Jest
        uses: BerniWittmann/background-server-action@v1.0.4
        with:
          build: npx fkill-cli :8080 OpenFin OpenFinRVM --force --silent
          start: npm run server --prefix how-to/register-with-home
          wait-on: 'http://localhost:8080/manifest.fin.json'
          command: npm run test-local-jest --prefix how-to/setup-automation-tests/examples/register-with-home-js
      - name: Run Server and TypeScript Tests with Mocha
        uses: BerniWittmann/background-server-action@v1.0.4
        with:
          build: npx fkill-cli :8080 OpenFin OpenFinRVM --force --silent
          start: npm run server --prefix how-to/register-with-home
          wait-on: 'http://localhost:8080/manifest.fin.json'
          command: npm run test-local-mocha --prefix how-to/setup-automation-tests/examples/register-with-home-ts
      - name: Run Server and TypeScript Tests with Jasmine
        uses: BerniWittmann/background-server-action@v1.0.4
        with:
          build: npx fkill-cli :8080 OpenFin OpenFinRVM --force --silent
          start: npm run server --prefix how-to/register-with-home
          wait-on: 'http://localhost:8080/manifest.fin.json'
          command: npm run test-local-jasmine --prefix how-to/setup-automation-tests/examples/register-with-home-ts
      - name: Run Server and TypeScript Tests with Jest
        uses: BerniWittmann/background-server-action@v1.0.4
        with:
          build: npx fkill-cli :8080 OpenFin OpenFinRVM --force --silent
          start: npm run server --prefix how-to/register-with-home
          wait-on: 'http://localhost:8080/manifest.fin.json'
          command: npm run test-local-jest --prefix how-to/setup-automation-tests/examples/register-with-home-ts
      - name: Run Selenium tests
        run: |
          cd how-to/setup-automation-tests/examples/selenium
          npm install
          npm run test
      - name: Run WDIO tests
        run: |
          cd how-to/setup-automation-tests/examples/wdio
          npm install
          npm run test
